name: mmgis
channels:
  - conda-forge
dependencies:
  - python==3.12
  - gdal==3.9.3
  - pip
  - pip:
      - numpy==2.1.0
      - requests==2.32.3
      - spiceypy==5.1.2
      - pymap3d==3.0.1
      - pypgstac==0.8.6
      - python-dotenv[cli]==1.0.1
      - uvicorn==0.30.6
      - psycopg[binary,pool]==3.2.1
      - stac-fastapi-pgstac==3.0.0
      - tipg==0.7.2
      - titiler.application==0.18.6
      - titiler-pgstac==1.4.0
